spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri:
              http://localhost:8081
            predicates:
              - Path =/customers/**
          - id:
              r2
            uri:
              http://localhost:8082
            predicates:
              - Path=/accounts/**
    discovery:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true



server:
  port: 8088
